### ISSUE TITLE
dataset_name - FileNotFoundError: [Errno 2] No such file or directory: 'tensor/W.pt'

### ISSUE THREAD

**Issue by johndpope** [soushirou/StyleCLIP-pytorch#6]
self.W = torch.load(f'tensor/W{dataset_name}.pt')
        self.S = torch.load(f'tensor/S{dataset_name}.pt')
        self.S_mean = torch.load(f'tensor/S_mean{dataset_name}.pt')
        self.S_std = torch.load(f'tensor/S_std{dataset_name}.pt')

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    manipulator = Manipulator(G, device)
  File "/home/jp/Documents/gitWorkspace/StyleCLIP-pytorch-1/manipulator.py", line 51, in __init__
    self.W = torch.load(f'tensor/W{dataset_name}.pt')
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'tensor/W.pt'

**Comment by JohnnyRacer** [comment]
DId you extract the W, S, S_mean, S_std using `extract.py ` first? The manipulator needs to load in these weights to perform the edits.
